<div class="container">
  <div class="span-17">
<h1>
 <?= $this->platform->getName(); ?> GAMES
 <img src="/images/<?= $this->platform->getAbbreviation(); ?>.png" alt="<?= $this->platform->getName(); ?>" style="padding-left: 10px;" /></a>
</h1>
<p>
GameNomad is currently tracking <b><?= $this->count; ?></b> <?= $this->platform->getName(); ?> games. 
Click on a game cover to learn more about it.<br />
</p>

<div class="pager">
<b>Page</b>: <?php echo $this->Pager($this->pages, $this->page, "/games/platform/{$this->platform->getAbbreviation()}"); ?>
</div>

<ul id="product_grid">

<?php foreach ($this->games AS $game) { ?>

<li>
  <a href="/games/<?= $game->getAsin(); ?>">
    <img src="<?= $game->getMedium(); ?>" class="game_cover" alt="" />
  </a><br />
  <b><a href="/games/<?= $game->getAsin(); ?>"><?= $game->getName(); ?></a></b>
</li>

<?php } ?>
</ul>

<div class="pager">
<b>Page</b>: <?php echo $this->Pager($this->pages, $this->page, "/games/platform/{$this->platform->getAbbreviation()}"); ?>
</div>

</div>

<div id="sidebar" class="span-7 last">

<?php echo $this->render('_book_ad.phtml') ?>

<h3>HOT <?= $this->platform->getName(); ?> GAMES</h3>

<?php foreach ($this->hotGames AS $hotGame) { ?>

<div class="game-sidebar">
<b><a href="/games/<?= $hotGame->getGame()->getAsin(); ?>"><?= $hotGame->getGame()->getName(); ?></a></b><br /> 
<b>Sales Rank</b>: #<?= $hotGame->getRank(); ?><br />
</div>

<?php } ?>

</div>
</div>
