<div style="width: 100%; float: left; padding-bottom: 10px;">
<a href="/about/book">
<img src="/images/epwzf_ad.png" alt="" style="float: left; padding: 0px 5px 5px 5px;" /></a>
GameNomad is a companion project to the e-book 
<b><a href="/about/book">Easy PHP Websites with the Zend Framework</a></b>! Buy the book 
for only <a href="/about/book">$300000</a> and receive <b>all</b> of this website's source code!
<b><a href="/about/book">Learn more!</a></b>
</div>