<?php 

$email = <<< email
Dear {$this->_request->getPost('name')},

{$this->_request->getPost('username')} would like you to consider joining GameNomad.com, the social networking site for gamers. Joining the site is free, and in doing so you'll be able to manage your video game library, keep tabs on your friends' libraries, and learn about new and newly popular games!

Thank you!
The GameNomad Team

Questions? Contact us at gamenomad@wjgilmore.com
http://gamenomad.wjgilmore.com/

email;

?>
