<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EntitiesAccountProxy extends \Entities\Account implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function addFriend(\Entities\Account $friend)
    {
        $this->_load();
        return parent::addFriend($friend);
    }

    public function getFriends()
    {
        $this->_load();
        return parent::getFriends();
    }

    public function addGame(\Entities\Game $game)
    {
        $this->_load();
        return parent::addGame($game);
    }

    public function getGames()
    {
        $this->_load();
        return parent::getGames();
    }

    public function updated()
    {
        $this->_load();
        return parent::updated();
    }

    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function getUsername()
    {
        $this->_load();
        return parent::getUsername();
    }

    public function setUsername($username)
    {
        $this->_load();
        return parent::setUsername($username);
    }

    public function getEmail()
    {
        $this->_load();
        return parent::getEmail();
    }

    public function setEmail($email)
    {
        $this->_load();
        return parent::setEmail($email);
    }

    public function getPassword()
    {
        $this->_load();
        return parent::getPassword();
    }

    public function setPassword($password)
    {
        $this->_load();
        return parent::setPassword($password);
    }

    public function getZip()
    {
        $this->_load();
        return parent::getZip();
    }

    public function setZip($zip)
    {
        $this->_load();
        return parent::setZip($zip);
    }

    public function getLatitude()
    {
        $this->_load();
        return parent::getLatitude();
    }

    public function setLatitude($latitude)
    {
        $this->_load();
        return parent::setLatitude($latitude);
    }

    public function getLongitude()
    {
        $this->_load();
        return parent::getLongitude();
    }

    public function setLongitude($longitude)
    {
        $this->_load();
        return parent::setLongitude($longitude);
    }

    public function getConfirmed()
    {
        $this->_load();
        return parent::getConfirmed();
    }

    public function setConfirmed($confirmed)
    {
        $this->_load();
        return parent::setConfirmed($confirmed);
    }

    public function getRecovery()
    {
        $this->_load();
        return parent::getRecovery();
    }

    public function setRecovery($recovery)
    {
        $this->_load();
        return parent::setRecovery($recovery);
    }

    public function getCreated()
    {
        $this->_load();
        return parent::getCreated();
    }

    public function setCreated($created)
    {
        $this->_load();
        return parent::setCreated($created);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'username', 'email', 'password', 'zip', 'latitude', 'longitude', 'confirmed', 'recovery', 'created', 'updated', 'games', 'friendsWithMe', 'myFriends');
    }
}