<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EntitiesRankProxy extends \Entities\Rank implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function setGame($game)
    {
        $this->_load();
        return parent::setGame($game);
    }

    public function getGame()
    {
        $this->_load();
        return parent::getGame();
    }

    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function getRank()
    {
        $this->_load();
        return parent::getRank();
    }

    public function setRank($rank)
    {
        $this->_load();
        return parent::setRank($rank);
    }

    public function getCreated()
    {
        $this->_load();
        return parent::getCreated();
    }

    public function setCreated($created)
    {
        $this->_load();
        return parent::setCreated($created);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'rank', 'game', 'created');
    }
}