<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EntitiesGameProxy extends \Entities\Game implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function updated()
    {
        $this->_load();
        return parent::updated();
    }

    public function addAccount(\Entities\Account $account)
    {
        $this->_load();
        return parent::addAccount($account);
    }

    public function getAccounts()
    {
        $this->_load();
        return parent::getAccounts();
    }

    public function getRanks()
    {
        $this->_load();
        return parent::getRanks();
    }

    public function getLatestRank()
    {
        $this->_load();
        return parent::getLatestRank();
    }

    public function setRank($rank)
    {
        $this->_load();
        return parent::setRank($rank);
    }

    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function getAsin()
    {
        $this->_load();
        return parent::getAsin();
    }

    public function setAsin($asin)
    {
        $this->_load();
        return parent::setAsin($asin);
    }

    public function getName()
    {
        $this->_load();
        return parent::getName();
    }

    public function setName($name)
    {
        $this->_load();
        return parent::setName($name);
    }

    public function getPlatform()
    {
        $this->_load();
        return parent::getPlatform();
    }

    public function getPublisher()
    {
        $this->_load();
        return parent::getPublisher();
    }

    public function setPublisher($publisher)
    {
        $this->_load();
        return parent::setPublisher($publisher);
    }

    public function getRelease()
    {
        $this->_load();
        return parent::getRelease();
    }

    public function setRelease($release)
    {
        $this->_load();
        return parent::setRelease($release);
    }

    public function getSmall()
    {
        $this->_load();
        return parent::getSmall();
    }

    public function setSmall($small)
    {
        $this->_load();
        return parent::setSmall($small);
    }

    public function getMedium()
    {
        $this->_load();
        return parent::getMedium();
    }

    public function setMedium($medium)
    {
        $this->_load();
        return parent::setMedium($medium);
    }

    public function getPrice()
    {
        $this->_load();
        return parent::getPrice();
    }

    public function setPrice($price)
    {
        $this->_load();
        return parent::setPrice($price);
    }

    public function getCreated()
    {
        $this->_load();
        return parent::getCreated();
    }

    public function setCreated($created)
    {
        $this->_load();
        return parent::setCreated($created);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'asin', 'name', 'publisher', 'rel', 'small', 'medium', 'price', 'created', 'updated', 'accounts', 'platform', 'ranks');
    }
}