<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;
use Doctrine\DBAL\Types\Type;

/**
 * Game
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Game extends EntityRepository
{
  
  /**
   * 
   * 
   */
  public function recentGames($count)
  {
    
    $rsm = new ResultSetMapping;
        
    $rsm->addEntityResult('Entities\Game', 'g');
    $rsm->addFieldResult('g', 'id', 'id');
    $rsm->addFieldResult('g', 'asin', 'asin');
    $rsm->addFieldResult('g', 'name', 'name');
    $rsm->addFieldResult('g', 'medium', 'medium');
    
    $query = $this->_em->createNativeQuery(
      'SELECT g.id, g.asin, g.name, g.medium FROM games g ORDER BY g.created DESC LIMIT ?',
       $rsm
    );    
        
    $query->setParameter(1, $count, Type::INTEGER);
    
    return $query->getResult();    
  }
  
}