<h1>About Easy PHP Websites with the Zend Framework</h1>

<div class="container">
  <div class="span-5">
<p>
<a href="http://www.wjgilmore.com/books/read/easy_php_websites_with_the_zend_framework"><img src="/images/epwzf_cover.png" alt="Easy PHP Websites with the Zend Framework" style="float: left; padding-right: 10px;" /></a><br />
<a href="http://www.wjgilmore.com/books/read/easy_php_websites_with_the_zend_framework"><b>Easy PHP Websites with the Zend Framework</b></a><br />
<b>Author</b>: W. Jason Gilmore<br />
<a href="http://www.wjgilmore.com">W.J. Gilmore, LLC</a> &middot; 2011<br />
$30 &middot; 300 pages <br /><br />
<a href="http://www.wjgilmore.com/books/read/easy_php_websites_with_the_zend_framework" class="button blue">Buy 
the eBook Now!</a>
</p>

<p>
Your purchase includes access to <b>all</b> of the source code used to power the GameNomad website.
</p>

</div>

<div class="span-18">
<p>
To paraphrase the ancient adage, "An example is worth 1,000 words". When I set out to write an introductory book to the <a href="http://framework.zend.com">Zend Framework</a>, I wanted to accompany the instruction with a thematic example which would not only keep the reader engaged, but which also incorporates many features which are found in modern websites. That example turned out to be GameNomad.
</p>

<p>
Many of GameNomad's features are described in <a href="http://www.wjgilmore.com/books/read/easy_php_websites_with_the_zend_framework">Easy PHP Websites with the Zend Framework</a>, complete with a contextual description and sample code. Among the many topics covered you'll learn how to:
</p>

<ul>
  <li>Effectively manage your Zend Framework layouts and views, and create view helpers which can be reused throughout your website</li>
  <li>Integrate <a href="http://www.doctrine-project.org/">Doctrine 2</a> into your Zend Framework application</li>
<li>Manage configuration data using the Zend Framework's <a href="http://framework.zend.com/manual/en/zend.config.html">Zend_Config</a> component</li>
<li>Build model-driven forms which can easily be tested using PHPUnit and Zend_Test</li>
<li>Mine the Amazon.com product catalog using the <a href="https://affiliate-program.amazon.com/gp/advertising/api/detail/main.html">Amazon Product Advertising API</a></li>
<li>Test your website using <a href="http://www.phpunit.de">PHPUnit</a> and <a href="http://framework.zend.com/manual/en/zend.test.html">Zend_Test</a></li>
<li>Deploy your website quickly and conveniently using <a href="http://phing.info/">Phing</a> and <a href="https://github.com/capistrano/capistrano">Capistrano</a></li>
<li>Write PHP-driven <a href="http://us.php.net/cli">CLI</a> scripts which can take advantage of Zend Framework components</li>
<li>And much, much, much more!</li>
</ul>

<p>
Remember that the primary goal of <a href="http://www.wjgilmore.com/books/read/easy_php_websites_with_the_zend_framework">Easy 
PHP Websites with the Zend Framework</a> is to help you master the Zend Framework, and not necessarily 
to build a social networking website for video gamers. Therefore not every GameNomad feature is covered 
in painstaking detail. However, because all readers receive <b>free access to all of the 
GameNomad source code</b> and <b>free book updates for life</b>, you'll be able to examine and then 
recreate every single feature found on this website.
</p>

<h3>Purchase the eBook</h3>
<p>
Available for just $30 from <a href="http://www.wjgilmore.com">WJGilmore.com</a>, and including all of the 
GameNomad.com source code, I guarantee this is the most effective way to master the Zend Framework you'll 
find anywhere.
</p>

<p>
<a href="http://www.wjgilmore.com/books/read/easy_php_websites_with_the_zend_framework" class="button blue">Buy 
the eBook Now!</a>
</p>

<h3>Purchase the Print Book</h3>

<p>
Following a few rounds of eBook feedback, a print book will be made available for sale via 
<a href="http://www.wjgilmore.com">WJGilmore.com</a>, Amazon.com, and other online outlets. Owners of
the eBook will have the opportunity to purchase the print book via WJGilmore.com at a very special price. 
</p>

<h3>About the Author</h3>
<p>
W. Jason Gilmore is a developer, consultant, and author of six books, including the bestselling 
"Beginning PHP and MySQL, Fourth Edition" (<a href="http://www.apress.com">Apress</a>, 2010), "Easy PHP 
Websites with the Zend Framework" (<a href="http://www.wjgilmore.com">W.J. Gilmore LLC</a>, 2009), and "Easy 
PayPal with PHP" (<a href="http://www.wjgilmore.com">W.J. Gilmore LLC</a>, 2009). He is a regular columnist 
for Developer.com, JS Magazine, and PHPBuilder.com, and has been published more than one hundred times over 
the years within leading online and print publications. Jason has instructed hundreds of developers in the 
United States and Europe.
</p>

<p>
Jason is co-founder of the popular CodeMash Conference 
<a href="http://www.codemash.org">http://www.codemash.org</a>), and was a member of the 2008 MySQL conference 
speaker selection board. 
</p>

<p>
<a href="/about/contact">E-mail</a> Jason with your questions and comments!
</p>
</div>
</div>


