<h1>Buy the Book and You Could Win a Copy of Homefront</h1>

<div class="container">
  <div class="span-5">
<p>
<a href="http://www.wjgilmore.com/books/read/easy_php_websites_with_the_zend_framework"><img src="/images/epwzf_cover.png" alt="Easy PHP Websites with the Zend Framework" style="float: left; padding-right: 10px;" /></a><br />
<a href="http://www.wjgilmore.com/books/read/easy_php_websites_with_the_zend_framework"><b>Easy PHP Websites with the Zend Framework</b></a><br />
<b>Author</b>: W. Jason Gilmore<br />
<a href="http://www.wjgilmore.com">W.J. Gilmore, LLC</a> &middot; 2011 
 &middot; $30 &middot; 300 pages <br /><br />
<a href="http://www.wjgilmore.com/books/read/easy_php_websites_with_the_zend_framework" class="button blue">Buy 
the eBook Now!</a>
</p>

<p>
Your purchase includes access to <b>all</b> of the source code used to power the GameNomad website.
</p>

</div>

<div class="span-18">

<p>
<a href="http://dev.gamenomad.com/games/B003Q53VZC"><img src="http://ecx.images-amazon.com/images/I/51nX6PoxgnL._SL160_.jpg" alt="Homefront" 
style="margin: 0px 5px 5px 0px; border: 1px solid black; float: left;" /></a>
To celebrate the release of 
<a href="http://www.wjgilmore.com/books/read/easy_php_websites_with_the_zend_framework">Easy PHP Websites
with the Zend Framework</a>, we're giving away a copy of 
<a href="http://www.homefront-game.com/">Homefront</a> to one lucky reader! Just purchase a copy of 
the book between now and March 30 and you'll automatically be entered!
</p>

<p>
The winner will be randomly drawn the first week of April and notified via e-mail. We'll buy whichever
console-specific version of Homefront the winner desires! 
</p>

<p>
Not ready to purchase the book but want to enter the contest anyway? No problem, just send us an e-mail at
contests@wjgilmore.com with the title <b>Homefront contest</b>. Be sure to include your name and e-mail address.
</p>

<p>
Contest only open to residents of the United States. 
</p>

</div>
</div>


