<h1>About GameNomad</h1>

<p>
<a href="http://www.wjgilmore.com/books/read/easy_php_websites_with_the_zend_framework"><img src="/images/epwzf_cover.png" alt="" style="float: left; padding: 5px 5px 5px 0px;" /></a>
GameNomad is the companion project to the book "<a href="http://www.wjgilmore.com/books/read/easy_php_websites_with_the_zend_framework">Easy PHP Websites with the Zend Framework</a>", authored by <a href="http://www.wjgilmore.com/about">Jason Gilmore</a> 
(GameNomad handle: <a href="/account/public/username/wjgilmore">wjgilmore</a>), an avid gamer, entrepreneur, 
writer, and web developer. All purchasers of "Easy PHP Websites with the Zend Framework" are provided 
with <b>all</b> of the source code used to power this website, in addition to access to several hours of 
companion video tutorials available at <a href="http://www.wjgilmore.com">WJGilmore.com</a>.
</p>

<p>
GameNomad makes it easy for you to organize your game collection according to platform, and set status flags for
each game, letting your friends know what games your playing, what games are currently being borrowed, and who
is borrowing other games. 
</p>

<p>
<a href="/about/contact">E-mail</a> Jason with your questions and comments!
</p>

<p>Happy Gaming!</p>

Jason<br />

