<h3>Why Create a GameNomad Account?</h3>

<p>
<a href="http://www.wjgilmore.com/books/read/easy_php_websites_with_the_zend_framework">
<img src="/images/epwzf_cover.png" alt="" style="float: left; padding: 5px 5px 5px 0px;" /></a>
GameNomad is the companion project to the book 
"<a href="http://www.wjgilmore.com/books/read/easy_php_websites_with_the_zend_framework">Easy PHP 
Websites with the Zend Framework</a>", authored by <a href="/account/public/username/wjgilmore">W. Jason Gilmore</a>
, an avid web developer, writer, gamer, and entrepreneur. All purchasers of 
"Easy PHP Websites with the Zend Framework" are provided with <b>all</b> of the source code used to 
power the GameNomad website.
</p>

<p>
Creating a GameNomad account will help to acquaint you with the features discussed throughout the book.
Registration is free, and only takes a moment! Once registered, be sure to login to your account and add
<a href="/account/public/username/wjgilmore">Jason</a> as a friend!
</p>